[package]
name = "blockchain-data-storage"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" # Or bincode, depending on serialization format
sha2 = "0.10"
hex = "0.4" # For representing hashes as strings

